language: node_js
node_js:
  - "0.8"

env:
  global:
    - NODE_ENV=testing

services: mongodb

before_install:
  - cd $TRAVIS_BUILD_DIR
  - cd src/app
  - npm install

script:
  - cd $TRAVIS_BUILD_DIR
  - make test
