language: node_js
node_js:
  - "0.8"

env:
  global:
    - NODE_ENV=testing

services: mongodb

before_install:
  - cd $TRAVIS_BUILD_DIR
  - npm install

before_script:
	- cd $TRAVIS_BUILD_DIR
  - npm install -d

script:
  - cd $TRAVIS_BUILD_DIR
  - make test
